import { EXCHANGE_ENDPOINTS, ITEMS_ENDPOINTS } from "@/constants/endpoints";
import { CATEGORY_NAMES_EXCHANGE, CATEGORY_NAMES_STASH } from "@/constants/sidebarItems";

import type { EntityPageConfig } from "@/types/config";

/** @TODO UPDATE THE UNDEFINED ROUTES. */
export const PAGE_CONFIG = {
  CURRENCY: {
    TITLE: "Currency",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.CURRENCY,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.CURRENCY,
      },
    },
  },
  CARD: {
    TITLE: "Cards",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.CARD,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.CARD,
      },
    },
  },
  FRAGMENT: {
    TITLE: "Fragments",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.FRAGMENT,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.FRAGMENT,
      },
    },
  },
  ESSENCE: {
    TITLE: "Essence",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.ESSENCE,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.ESSENCE,
      },
    },
  },
  INCUBATOR: {
    TITLE: "Incubator",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.INCUBATOR,
      },
    },
  },
  OIL: {
    TITLE: "Oil",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.OIL,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.OIL,
      },
    },
  },
  FOSSIL: {
    TITLE: "Fossil",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.FOSSIL,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.DELVE,
      },
    },
  },
  BEAST: {
    TITLE: "Beasts",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.BEAST,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.HEIST,
      },
    },
  },
  HEIST: {
    TITLE: "Heists",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.HEIST,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.HEIST,
      },
    },
  },
} as const satisfies Record<string, EntityPageConfig>;
