import { EXCHANGE_ENDPOINTS, ITEMS_ENDPOINTS } from "@/constants/endpoints";
import { CATEGORY_NAMES_EXCHANGE, CATEGORY_NAMES_STASH } from "@/constants/sidebarItems";

import type { EntityPageConfig } from "@/types/config";

/** @TODO UPDATE THE UNDEFINED ROUTES. */
export const PAGE_CONFIG = {
  /** @GENERAL */
  CURRENCY: {
    TITLE: "Currency",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.CURRENCY,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.CURRENCY,
      },
    },
  },
  CARD: {
    TITLE: "Cards",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.CARD,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.CARD,
      },
    },
  },
  FRAGMENT: {
    TITLE: "Fragments",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.FRAGMENT,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.FRAGMENT,
      },
    },
  },
  ESSENCE: {
    TITLE: "Essence",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.ESSENCE,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.ESSENCE,
      },
    },
  },
  INCUBATOR: {
    TITLE: "Incubator",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.INCUBATOR,
      },
    },
  },
  OIL: {
    TITLE: "Oil",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.OIL,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.OIL,
      },
    },
  },
  FOSSIL: {
    TITLE: "Fossil",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.FOSSIL,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.DELVE,
      },
    },
  },
  BEAST: {
    TITLE: "Beasts",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.BEAST,
      },
    },
  },
  HEIST: {
    TITLE: "Heists",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.HEIST,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.HEIST,
      },
    },
  },
  /** @EQUIPMENT & GEMS */
  ARMOUR: {
    TITLE: "Armour",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.ARMOUR,
      },
    },
  },
  WEAPONS: {
    TITLE: "Weapons",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.WEAPON,
      },
    },
  },
  GEMS: {
    TITLE: "Gems",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.GEM,
      },
    },
  },
  ACCESSORIES: {
    TITLE: "Accessories",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.ACCESSORY,
      },
    },
  },
  CRAFTING_BASES: {
    TITLE: "Crafting Bases",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.BASES,
      },
    },
  },
  JEWELS: {
    TITLE: "Jewels",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.JEWEL,
      },
    },
  },
  FLASKS: {
    TITLE: "Flasks",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.FLASK,
      },
    },
  },
  /** @ATLAS */
  MAPS: {
    TITLE: "Maps",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.MAP,
      },
    },
  },
  UNIQUE_MAPS: {
    TITLE: "Unique Maps",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.UNIQUE_MAP,
      },
    },
  },
  SCARABS: {
    TITLE: "Scarabs",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.SCARAB,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.SCARAB,
      },
    },
  },
  DELIRIUM_ORBS: {
    TITLE: "Delirium Orbs",
    MODES: {
      STASH: {
        ENDPOINT: ITEMS_ENDPOINTS.GET,
        FILTER_CATEGORY: CATEGORY_NAMES_STASH.DELIRIUM_ORB,
      },
      EXCHANGE: {
        ENDPOINT: EXCHANGE_ENDPOINTS.EXCHANGES_RATIOS,
        FILTER_CATEGORY: CATEGORY_NAMES_EXCHANGE.DELIRIUM,
      },
    },
  },
} as const satisfies Record<string, EntityPageConfig>;
