/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeLayoutRouteImport } from './routes/(home)/layout'
import { Route as economyLayoutRouteImport } from './routes/(economy)/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as homeLeaguesRouteImport } from './routes/(home)/leagues'
import { Route as economygeneralOilRouteImport } from './routes/(economy)/(general)/oil'
import { Route as economygeneralIncubatorRouteImport } from './routes/(economy)/(general)/incubator'
import { Route as economygeneralHeistRouteImport } from './routes/(economy)/(general)/heist'
import { Route as economygeneralFragmentRouteImport } from './routes/(economy)/(general)/fragment'
import { Route as economygeneralFossilRouteImport } from './routes/(economy)/(general)/fossil'
import { Route as economygeneralEssenceRouteImport } from './routes/(economy)/(general)/essence'
import { Route as economygeneralCurrencyRouteImport } from './routes/(economy)/(general)/currency'
import { Route as economygeneralCardRouteImport } from './routes/(economy)/(general)/card'
import { Route as economygeneralBeastRouteImport } from './routes/(economy)/(general)/beast'
import { Route as economyequipment_gemsWeaponRouteImport } from './routes/(economy)/(equipment_gems)/weapon'
import { Route as economyequipment_gemsJewelRouteImport } from './routes/(economy)/(equipment_gems)/jewel'
import { Route as economyequipment_gemsGemRouteImport } from './routes/(economy)/(equipment_gems)/gem'
import { Route as economyequipment_gemsFlaskRouteImport } from './routes/(economy)/(equipment_gems)/flask'
import { Route as economyequipment_gemsBasesRouteImport } from './routes/(economy)/(equipment_gems)/bases'
import { Route as economyequipment_gemsArmourRouteImport } from './routes/(economy)/(equipment_gems)/armour'
import { Route as economyequipment_gemsAccessoryRouteImport } from './routes/(economy)/(equipment_gems)/accessory'
import { Route as economyatlasUniqueMapRouteImport } from './routes/(economy)/(atlas)/uniqueMap'
import { Route as economyatlasScarabRouteImport } from './routes/(economy)/(atlas)/scarab'
import { Route as economyatlasMapRouteImport } from './routes/(economy)/(atlas)/map'
import { Route as economyatlasDeliriumOrbRouteImport } from './routes/(economy)/(atlas)/deliriumOrb'

const homeLayoutRoute = homeLayoutRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const economyLayoutRoute = economyLayoutRouteImport.update({
  id: '/(economy)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLeaguesRoute = homeLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => homeLayoutRoute,
} as any)
const economygeneralOilRoute = economygeneralOilRouteImport.update({
  id: '/(general)/oil',
  path: '/oil',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralIncubatorRoute = economygeneralIncubatorRouteImport.update({
  id: '/(general)/incubator',
  path: '/incubator',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralHeistRoute = economygeneralHeistRouteImport.update({
  id: '/(general)/heist',
  path: '/heist',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralFragmentRoute = economygeneralFragmentRouteImport.update({
  id: '/(general)/fragment',
  path: '/fragment',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralFossilRoute = economygeneralFossilRouteImport.update({
  id: '/(general)/fossil',
  path: '/fossil',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralEssenceRoute = economygeneralEssenceRouteImport.update({
  id: '/(general)/essence',
  path: '/essence',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralCurrencyRoute = economygeneralCurrencyRouteImport.update({
  id: '/(general)/currency',
  path: '/currency',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralCardRoute = economygeneralCardRouteImport.update({
  id: '/(general)/card',
  path: '/card',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economygeneralBeastRoute = economygeneralBeastRouteImport.update({
  id: '/(general)/beast',
  path: '/beast',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economyequipment_gemsWeaponRoute =
  economyequipment_gemsWeaponRouteImport.update({
    id: '/(equipment_gems)/weapon',
    path: '/weapon',
    getParentRoute: () => economyLayoutRoute,
  } as any)
const economyequipment_gemsJewelRoute =
  economyequipment_gemsJewelRouteImport.update({
    id: '/(equipment_gems)/jewel',
    path: '/jewel',
    getParentRoute: () => economyLayoutRoute,
  } as any)
const economyequipment_gemsGemRoute =
  economyequipment_gemsGemRouteImport.update({
    id: '/(equipment_gems)/gem',
    path: '/gem',
    getParentRoute: () => economyLayoutRoute,
  } as any)
const economyequipment_gemsFlaskRoute =
  economyequipment_gemsFlaskRouteImport.update({
    id: '/(equipment_gems)/flask',
    path: '/flask',
    getParentRoute: () => economyLayoutRoute,
  } as any)
const economyequipment_gemsBasesRoute =
  economyequipment_gemsBasesRouteImport.update({
    id: '/(equipment_gems)/bases',
    path: '/bases',
    getParentRoute: () => economyLayoutRoute,
  } as any)
const economyequipment_gemsArmourRoute =
  economyequipment_gemsArmourRouteImport.update({
    id: '/(equipment_gems)/armour',
    path: '/armour',
    getParentRoute: () => economyLayoutRoute,
  } as any)
const economyequipment_gemsAccessoryRoute =
  economyequipment_gemsAccessoryRouteImport.update({
    id: '/(equipment_gems)/accessory',
    path: '/accessory',
    getParentRoute: () => economyLayoutRoute,
  } as any)
const economyatlasUniqueMapRoute = economyatlasUniqueMapRouteImport.update({
  id: '/(atlas)/uniqueMap',
  path: '/uniqueMap',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economyatlasScarabRoute = economyatlasScarabRouteImport.update({
  id: '/(atlas)/scarab',
  path: '/scarab',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economyatlasMapRoute = economyatlasMapRouteImport.update({
  id: '/(atlas)/map',
  path: '/map',
  getParentRoute: () => economyLayoutRoute,
} as any)
const economyatlasDeliriumOrbRoute = economyatlasDeliriumOrbRouteImport.update({
  id: '/(atlas)/deliriumOrb',
  path: '/deliriumOrb',
  getParentRoute: () => economyLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leagues': typeof homeLeaguesRoute
  '/deliriumOrb': typeof economyatlasDeliriumOrbRoute
  '/map': typeof economyatlasMapRoute
  '/scarab': typeof economyatlasScarabRoute
  '/uniqueMap': typeof economyatlasUniqueMapRoute
  '/accessory': typeof economyequipment_gemsAccessoryRoute
  '/armour': typeof economyequipment_gemsArmourRoute
  '/bases': typeof economyequipment_gemsBasesRoute
  '/flask': typeof economyequipment_gemsFlaskRoute
  '/gem': typeof economyequipment_gemsGemRoute
  '/jewel': typeof economyequipment_gemsJewelRoute
  '/weapon': typeof economyequipment_gemsWeaponRoute
  '/beast': typeof economygeneralBeastRoute
  '/card': typeof economygeneralCardRoute
  '/currency': typeof economygeneralCurrencyRoute
  '/essence': typeof economygeneralEssenceRoute
  '/fossil': typeof economygeneralFossilRoute
  '/fragment': typeof economygeneralFragmentRoute
  '/heist': typeof economygeneralHeistRoute
  '/incubator': typeof economygeneralIncubatorRoute
  '/oil': typeof economygeneralOilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leagues': typeof homeLeaguesRoute
  '/deliriumOrb': typeof economyatlasDeliriumOrbRoute
  '/map': typeof economyatlasMapRoute
  '/scarab': typeof economyatlasScarabRoute
  '/uniqueMap': typeof economyatlasUniqueMapRoute
  '/accessory': typeof economyequipment_gemsAccessoryRoute
  '/armour': typeof economyequipment_gemsArmourRoute
  '/bases': typeof economyequipment_gemsBasesRoute
  '/flask': typeof economyequipment_gemsFlaskRoute
  '/gem': typeof economyequipment_gemsGemRoute
  '/jewel': typeof economyequipment_gemsJewelRoute
  '/weapon': typeof economyequipment_gemsWeaponRoute
  '/beast': typeof economygeneralBeastRoute
  '/card': typeof economygeneralCardRoute
  '/currency': typeof economygeneralCurrencyRoute
  '/essence': typeof economygeneralEssenceRoute
  '/fossil': typeof economygeneralFossilRoute
  '/fragment': typeof economygeneralFragmentRoute
  '/heist': typeof economygeneralHeistRoute
  '/incubator': typeof economygeneralIncubatorRoute
  '/oil': typeof economygeneralOilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(economy)': typeof economyLayoutRouteWithChildren
  '/(home)': typeof homeLayoutRouteWithChildren
  '/(home)/leagues': typeof homeLeaguesRoute
  '/(economy)/(atlas)/deliriumOrb': typeof economyatlasDeliriumOrbRoute
  '/(economy)/(atlas)/map': typeof economyatlasMapRoute
  '/(economy)/(atlas)/scarab': typeof economyatlasScarabRoute
  '/(economy)/(atlas)/uniqueMap': typeof economyatlasUniqueMapRoute
  '/(economy)/(equipment_gems)/accessory': typeof economyequipment_gemsAccessoryRoute
  '/(economy)/(equipment_gems)/armour': typeof economyequipment_gemsArmourRoute
  '/(economy)/(equipment_gems)/bases': typeof economyequipment_gemsBasesRoute
  '/(economy)/(equipment_gems)/flask': typeof economyequipment_gemsFlaskRoute
  '/(economy)/(equipment_gems)/gem': typeof economyequipment_gemsGemRoute
  '/(economy)/(equipment_gems)/jewel': typeof economyequipment_gemsJewelRoute
  '/(economy)/(equipment_gems)/weapon': typeof economyequipment_gemsWeaponRoute
  '/(economy)/(general)/beast': typeof economygeneralBeastRoute
  '/(economy)/(general)/card': typeof economygeneralCardRoute
  '/(economy)/(general)/currency': typeof economygeneralCurrencyRoute
  '/(economy)/(general)/essence': typeof economygeneralEssenceRoute
  '/(economy)/(general)/fossil': typeof economygeneralFossilRoute
  '/(economy)/(general)/fragment': typeof economygeneralFragmentRoute
  '/(economy)/(general)/heist': typeof economygeneralHeistRoute
  '/(economy)/(general)/incubator': typeof economygeneralIncubatorRoute
  '/(economy)/(general)/oil': typeof economygeneralOilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leagues'
    | '/deliriumOrb'
    | '/map'
    | '/scarab'
    | '/uniqueMap'
    | '/accessory'
    | '/armour'
    | '/bases'
    | '/flask'
    | '/gem'
    | '/jewel'
    | '/weapon'
    | '/beast'
    | '/card'
    | '/currency'
    | '/essence'
    | '/fossil'
    | '/fragment'
    | '/heist'
    | '/incubator'
    | '/oil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leagues'
    | '/deliriumOrb'
    | '/map'
    | '/scarab'
    | '/uniqueMap'
    | '/accessory'
    | '/armour'
    | '/bases'
    | '/flask'
    | '/gem'
    | '/jewel'
    | '/weapon'
    | '/beast'
    | '/card'
    | '/currency'
    | '/essence'
    | '/fossil'
    | '/fragment'
    | '/heist'
    | '/incubator'
    | '/oil'
  id:
    | '__root__'
    | '/'
    | '/(economy)'
    | '/(home)'
    | '/(home)/leagues'
    | '/(economy)/(atlas)/deliriumOrb'
    | '/(economy)/(atlas)/map'
    | '/(economy)/(atlas)/scarab'
    | '/(economy)/(atlas)/uniqueMap'
    | '/(economy)/(equipment_gems)/accessory'
    | '/(economy)/(equipment_gems)/armour'
    | '/(economy)/(equipment_gems)/bases'
    | '/(economy)/(equipment_gems)/flask'
    | '/(economy)/(equipment_gems)/gem'
    | '/(economy)/(equipment_gems)/jewel'
    | '/(economy)/(equipment_gems)/weapon'
    | '/(economy)/(general)/beast'
    | '/(economy)/(general)/card'
    | '/(economy)/(general)/currency'
    | '/(economy)/(general)/essence'
    | '/(economy)/(general)/fossil'
    | '/(economy)/(general)/fragment'
    | '/(economy)/(general)/heist'
    | '/(economy)/(general)/incubator'
    | '/(economy)/(general)/oil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  economyLayoutRoute: typeof economyLayoutRouteWithChildren
  homeLayoutRoute: typeof homeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(economy)': {
      id: '/(economy)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof economyLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/leagues': {
      id: '/(home)/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof homeLeaguesRouteImport
      parentRoute: typeof homeLayoutRoute
    }
    '/(economy)/(general)/oil': {
      id: '/(economy)/(general)/oil'
      path: '/oil'
      fullPath: '/oil'
      preLoaderRoute: typeof economygeneralOilRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/incubator': {
      id: '/(economy)/(general)/incubator'
      path: '/incubator'
      fullPath: '/incubator'
      preLoaderRoute: typeof economygeneralIncubatorRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/heist': {
      id: '/(economy)/(general)/heist'
      path: '/heist'
      fullPath: '/heist'
      preLoaderRoute: typeof economygeneralHeistRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/fragment': {
      id: '/(economy)/(general)/fragment'
      path: '/fragment'
      fullPath: '/fragment'
      preLoaderRoute: typeof economygeneralFragmentRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/fossil': {
      id: '/(economy)/(general)/fossil'
      path: '/fossil'
      fullPath: '/fossil'
      preLoaderRoute: typeof economygeneralFossilRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/essence': {
      id: '/(economy)/(general)/essence'
      path: '/essence'
      fullPath: '/essence'
      preLoaderRoute: typeof economygeneralEssenceRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/currency': {
      id: '/(economy)/(general)/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof economygeneralCurrencyRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/card': {
      id: '/(economy)/(general)/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof economygeneralCardRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(general)/beast': {
      id: '/(economy)/(general)/beast'
      path: '/beast'
      fullPath: '/beast'
      preLoaderRoute: typeof economygeneralBeastRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(equipment_gems)/weapon': {
      id: '/(economy)/(equipment_gems)/weapon'
      path: '/weapon'
      fullPath: '/weapon'
      preLoaderRoute: typeof economyequipment_gemsWeaponRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(equipment_gems)/jewel': {
      id: '/(economy)/(equipment_gems)/jewel'
      path: '/jewel'
      fullPath: '/jewel'
      preLoaderRoute: typeof economyequipment_gemsJewelRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(equipment_gems)/gem': {
      id: '/(economy)/(equipment_gems)/gem'
      path: '/gem'
      fullPath: '/gem'
      preLoaderRoute: typeof economyequipment_gemsGemRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(equipment_gems)/flask': {
      id: '/(economy)/(equipment_gems)/flask'
      path: '/flask'
      fullPath: '/flask'
      preLoaderRoute: typeof economyequipment_gemsFlaskRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(equipment_gems)/bases': {
      id: '/(economy)/(equipment_gems)/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof economyequipment_gemsBasesRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(equipment_gems)/armour': {
      id: '/(economy)/(equipment_gems)/armour'
      path: '/armour'
      fullPath: '/armour'
      preLoaderRoute: typeof economyequipment_gemsArmourRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(equipment_gems)/accessory': {
      id: '/(economy)/(equipment_gems)/accessory'
      path: '/accessory'
      fullPath: '/accessory'
      preLoaderRoute: typeof economyequipment_gemsAccessoryRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(atlas)/uniqueMap': {
      id: '/(economy)/(atlas)/uniqueMap'
      path: '/uniqueMap'
      fullPath: '/uniqueMap'
      preLoaderRoute: typeof economyatlasUniqueMapRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(atlas)/scarab': {
      id: '/(economy)/(atlas)/scarab'
      path: '/scarab'
      fullPath: '/scarab'
      preLoaderRoute: typeof economyatlasScarabRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(atlas)/map': {
      id: '/(economy)/(atlas)/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof economyatlasMapRouteImport
      parentRoute: typeof economyLayoutRoute
    }
    '/(economy)/(atlas)/deliriumOrb': {
      id: '/(economy)/(atlas)/deliriumOrb'
      path: '/deliriumOrb'
      fullPath: '/deliriumOrb'
      preLoaderRoute: typeof economyatlasDeliriumOrbRouteImport
      parentRoute: typeof economyLayoutRoute
    }
  }
}

interface economyLayoutRouteChildren {
  economyatlasDeliriumOrbRoute: typeof economyatlasDeliriumOrbRoute
  economyatlasMapRoute: typeof economyatlasMapRoute
  economyatlasScarabRoute: typeof economyatlasScarabRoute
  economyatlasUniqueMapRoute: typeof economyatlasUniqueMapRoute
  economyequipment_gemsAccessoryRoute: typeof economyequipment_gemsAccessoryRoute
  economyequipment_gemsArmourRoute: typeof economyequipment_gemsArmourRoute
  economyequipment_gemsBasesRoute: typeof economyequipment_gemsBasesRoute
  economyequipment_gemsFlaskRoute: typeof economyequipment_gemsFlaskRoute
  economyequipment_gemsGemRoute: typeof economyequipment_gemsGemRoute
  economyequipment_gemsJewelRoute: typeof economyequipment_gemsJewelRoute
  economyequipment_gemsWeaponRoute: typeof economyequipment_gemsWeaponRoute
  economygeneralBeastRoute: typeof economygeneralBeastRoute
  economygeneralCardRoute: typeof economygeneralCardRoute
  economygeneralCurrencyRoute: typeof economygeneralCurrencyRoute
  economygeneralEssenceRoute: typeof economygeneralEssenceRoute
  economygeneralFossilRoute: typeof economygeneralFossilRoute
  economygeneralFragmentRoute: typeof economygeneralFragmentRoute
  economygeneralHeistRoute: typeof economygeneralHeistRoute
  economygeneralIncubatorRoute: typeof economygeneralIncubatorRoute
  economygeneralOilRoute: typeof economygeneralOilRoute
}

const economyLayoutRouteChildren: economyLayoutRouteChildren = {
  economyatlasDeliriumOrbRoute: economyatlasDeliriumOrbRoute,
  economyatlasMapRoute: economyatlasMapRoute,
  economyatlasScarabRoute: economyatlasScarabRoute,
  economyatlasUniqueMapRoute: economyatlasUniqueMapRoute,
  economyequipment_gemsAccessoryRoute: economyequipment_gemsAccessoryRoute,
  economyequipment_gemsArmourRoute: economyequipment_gemsArmourRoute,
  economyequipment_gemsBasesRoute: economyequipment_gemsBasesRoute,
  economyequipment_gemsFlaskRoute: economyequipment_gemsFlaskRoute,
  economyequipment_gemsGemRoute: economyequipment_gemsGemRoute,
  economyequipment_gemsJewelRoute: economyequipment_gemsJewelRoute,
  economyequipment_gemsWeaponRoute: economyequipment_gemsWeaponRoute,
  economygeneralBeastRoute: economygeneralBeastRoute,
  economygeneralCardRoute: economygeneralCardRoute,
  economygeneralCurrencyRoute: economygeneralCurrencyRoute,
  economygeneralEssenceRoute: economygeneralEssenceRoute,
  economygeneralFossilRoute: economygeneralFossilRoute,
  economygeneralFragmentRoute: economygeneralFragmentRoute,
  economygeneralHeistRoute: economygeneralHeistRoute,
  economygeneralIncubatorRoute: economygeneralIncubatorRoute,
  economygeneralOilRoute: economygeneralOilRoute,
}

const economyLayoutRouteWithChildren = economyLayoutRoute._addFileChildren(
  economyLayoutRouteChildren,
)

interface homeLayoutRouteChildren {
  homeLeaguesRoute: typeof homeLeaguesRoute
}

const homeLayoutRouteChildren: homeLayoutRouteChildren = {
  homeLeaguesRoute: homeLeaguesRoute,
}

const homeLayoutRouteWithChildren = homeLayoutRoute._addFileChildren(
  homeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  economyLayoutRoute: economyLayoutRouteWithChildren,
  homeLayoutRoute: homeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
